# Generated by Django 5.2 on 2025-05-29 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_teammembership_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterConstraint(
            model_name='teammembership',
            name='one_team_per_user',
            constraint=models.UniqueConstraint(fields=('user',), name='one_team_per_user', violation_error_message='A user can only be part of one team at a time.'),
        ),
    ]
