# Generated by Django 5.2 on 2025-05-30 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_alter_team_leader_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='workers',
            new_name='membership_users',
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'leader')), fields=('user',), name='one_leader_per_user_in_team', violation_error_message='a user can be leader only once in a team, in case he is added to the team twice which is impossible-unique constraint of teammembership.'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'leader')), fields=('team', 'user'), name='one_user_leader_only_once_one_team', violation_error_message='A user can only be leader of one team at a time-unique constraint of teammembership.'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'leader')), fields=('team',), name='one_leader_per_team', violation_error_message='all team can have only 1 leader-unique constraint of teammembership.'),
        ),
        migrations.AlterConstraint(
            model_name='teammembership',
            name='one_team_per_user',
            constraint=models.UniqueConstraint(fields=('user',), name='one_team_per_user', violation_error_message='A user can only be part of one team at a time-unique constraint of teammembership.'),
        ),
    ]
