# Generated by Django 5.2 on 2025-05-31 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_rename_workers_team_membership_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_codes', to='permissions.team'),
        ),
        migrations.AddConstraint(
            model_name='accesscode',
            constraint=models.UniqueConstraint(fields=('team',), name='one_code_per_team', violation_error_message='Only one code per team is allowed-unique constraint for access code'),
        ),
    ]
