# Generated by Django 5.2 on 2025-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
