# Generated by Django 5.2 on 2025-05-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fts_app', '0003_file_owner_username_at_creation_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='fts_app.tag'),
        ),
    ]
