# Generated by Django 5.2 on 2025-05-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fts_app', '0004_alter_file_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='tags',
        ),
    ]
