# Generated by Django 5.2 on 2025-05-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fts_app', '0005_remove_file_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='fts_app.tag'),
        ),
    ]
