# Generated by Django 5.2 on 2025-05-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fts_app', '0006_file_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='method',
            field=models.CharField(blank=True, default='downloaded', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='permissions_at_modification',
            field=models.CharField(blank=True, default='read', max_length=255, null=True),
        ),
    ]
