# Generated by Django 5.2 on 2025-05-27 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fts_app', '0007_alter_modification_method_and_more'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='access_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='permissions.accesscode'),
        ),
        migrations.AddField(
            model_name='folder',
            name='access_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='permissions.accesscode'),
        ),
    ]
